export default {
  "login": "anmolahuja03",
  "id": 66223928,
  "node_id": "MDQ6VXNlcjY2MjIzOTI4",
  "avatar_url": "https://avatars.githubusercontent.com/u/66223928?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/anmolahuja03",
  "html_url": "https://github.com/anmolahuja03",
  "followers_url": "https://api.github.com/users/anmolahuja03/followers",
  "following_url": "https://api.github.com/users/anmolahuja03/following{/other_user}",
  "gists_url": "https://api.github.com/users/anmolahuja03/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/anmolahuja03/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/anmolahuja03/subscriptions",
  "organizations_url": "https://api.github.com/users/anmolahuja03/orgs",
  "repos_url": "https://api.github.com/users/anmolahuja03/repos",
  "events_url": "https://api.github.com/users/anmolahuja03/events{/privacy}",
  "received_events_url": "https://api.github.com/users/anmolahuja03/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Anmol Ahuja",
  "company": null,
  "blog": "",
  "location": "India",
  "email": null,
  "hireable": null,
  "bio": "Tech Content @ tekbook.io | WIP'21 GHC'21 Student Scholar | Web Developer",
  "twitter_username": null,
  "public_repos": 8,
  "public_gists": 0,
  "followers": 2,
  "following": 7,
  "created_at": "2020-05-31T21:13:09Z",
  "updated_at": "2021-09-09T09:33:47Z"
};